python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GCN --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 1 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 2 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 16 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 32 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
python training_singletask_model_5_final_better_reporting.py --gnn GraphConv --num_layers 3 --num_nodes 64 
